import Image1 from "../assets/project1.png"


export const data=[
    {
        id:1,
        category:'WEB',
        image:Image1,
        title:'Blog Application(React JS)',
        description:'A blog application created with the help of React JS in the client and Node JS along with its supperting libraries in the backend and Mongo DB for the database of the application',
        demo:'https://github.com/ShivanshMehtaa/MERN_BLOG_API',
        github:'https://github.com/ShivanshMehtaa/MERN_BLOG_API',
    },
    {
        id:2,
        category:'WEB',
        image:Image1,
        title:'HelpeR(Next JS)',
        description:"HelpeR is a ticket generation application for MNC's  where one department can generate tickets/issues and ask for there solution and can assign the severity of the issue as well. Helper uses NextJS framework for the frontend and backend and Mongo DB for the database",
        demo:'https://github.com/ShivanshMehtaa/HelpeR',
        github:'https://github.com/ShivanshMehtaa/HelpeR',
    },
    {
        id:3,
        category:'WEB',
        image:Image1,
        title:'Promptopia (Next JS)',
        description:'Promoptopia is a AI prompt sharing app where people can share their prompts with the output they recieved with everyone visiting the site. Promptopia uses Next JS in the frontend and backend and Mongo DB in the backend',
        demo:'https://github.com/ShivanshMehtaa/Promptopia',
        github:'https://github.com/ShivanshMehtaa/Promptopia',
    },
    {
        id:4,
        category:'WEB',
        image:Image1,
        title:'Unico Foods (React JS)',
        description:'Unico Foods is an Ecommerce WEBsite that focuses on selling goods made up of millets. Unico Foods uses React JS in the client and Node JS and its supporting libraries in the backend along with Mongo DB in the backend.',
        demo:'https://github.com/ShivanshMehtaa/Unico-v3',
        github:'https://github.com/ShivanshMehtaa/Unico-v3',
    },
    {
        id:5,
        category:'WEB',
        image:Image1,
        title:'Second Buys(React JS)',
        description:'Second Buys is a second hand goods purchasing application where people can list their used goods for sale at a discounted price. Second Buys uses react Js in the client and FireBase in the backend as well as the database.',
        demo:'https://secondbuys.vercel.app/',
        github:'https://github.com/ShivanshMehtaa/EComFirebase',
    },
    {
        id:6,
        category:'WEB',
        image:Image1,
        title:'ChatApplication(React JS)',
        description:'A common room chat application made with the help of React JS in the client  and Firebase for the backend as well as the database',
        demo:'https://6419df8006406e0094b3de88--splendid-travesseiro-c7f28e.netlify.app/',
        github:'https://github.com/ShivanshMehtaa/ChatApplication',
    },
    {
        id:7,
        category:'ML',
        image:Image1,
        title:'MediBuddy (Disease Prediction System)',
        description:'Medibuddy is a disease prediction system that uses Deep learning technologies to predict wether the person is suffering from the given disease or not. Currently it can predict Pneumonia and Brain Tumor.',
        demo:'https://github.com/ShivanshMehtaa/FlowerPred/tree/master',
        github:'https://github.com/ShivanshMehtaa/FlowerPred/tree/master',
    },
    {
        id:8,
        category:'ML',
        image:Image1,
        title:'Flower Prediction System (classification)',
        description:'This flower Prediction System classifies the flower type(currently 3) from the data given by the user. It uses Flask in the clien and a machine learning model runs in the background',
        demo:'https://github.com/ShivanshMehtaa/FlowerPred/tree/master',
        github:'https://github.com/ShivanshMehtaa/FlowerPred/tree/master',
    },
    {
        id:9,
        category:'ML',
        image:Image1,
        title:'Sentiment Analysis(NLP)',
        description:'A sentiment analysis project made with NLP that can prediict the emotion in the text using the Logistic Regression model ',
        demo:'https://github.com/ShivanshMehtaa/Sentiment-Analysis',
        github:'https://github.com/ShivanshMehtaa/Sentiment-Analysis',
    },
    {
        id:10,
        category:'ML',
        image:Image1,
        title:'Mevie Recommendation System',
        description:'A movie recommendation system that gives you the list of top 5 most matcheed movies based on the movie you liked',
        demo:'https://github.com/ShivanshMehtaa/Movie-Prediction-System',
        github:'https://github.com/ShivanshMehtaa/Movie-Prediction-System',
    },
    {
        id:11,
        category:'APP',
        image:Image1,
        title:'News App',
        description:'A simple application that fetches data from the news API and displays it on the frontend made using React Native, however there is also a search query provides where you can search for a category or a particular article',
        demo:'https://github.com/ShivanshMehtaa/Movie-Prediction-System',
        github:'https://github.com/ShivanshMehtaa/Movie-Prediction-System',
    },
    
    

]